### ISSUE TITLE
small.mzMLb might have wrong/missing version string?

### ISSUE THREAD

**Issue by timosachsenberg** [mobiusklein/mzdata#1]
Hi!
I am currently looking into mzMLb for OpenMS and I base my implementation on pwiz as a reference.
My code failed on your file so I double-checked if pwiz can load it and I get a similar error:

```
Starting...
Failed - System.Exception: [Connection_mzMLb::open()] Cannot read this version of mzMLb: "��;" (or version is not fixed-length string); only mzMLb 1.0 is supported
   at pwiz.CLI.msdata.ReaderList.read(String filename, MSDataList results, ReaderConfig config)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)
```

just an observation... not sure if relevant :)
kudos
Timo

**Comment by mobiusklein** [comment]
Thank you for pointing this out. The mzMLb file was written prior to the ProteoWizard implementation, the implementation in `mzdata` can read/write files compatible with ProteoWizard. I've regenerated the `small.mzMLb` file with ProteoWizard for future testing.
