### ISSUE TITLE
MGF: Two blank lines at the end of an MGF file lead an additional empty spectrum

### ISSUE THREAD

**Issue by RalfG** [mobiusklein/mzdata#3]
A minor issue, but one that could lead to some confusion downstream. When reading an MGF file with more than one blank lines at the end of the file, the MGF reader returns an additional empty spectrum.

**Comment by mobiusklein** [comment]
Thank you for reporting this. I'll look into it.

**Comment by mobiusklein** [comment]
It turned out to be the result of a tortured state machine I implemented poorly while learning the language last year. The state machine still isn't ideal, but should not longer have this issue.

**Comment by RalfG** [comment]
Thanks!
